server:
  port: 8051
spring:
  application:
    name: service-order
  #hikari 连接池
  datasource:
    url: jdbc:mysql://172.16.1.22:3306/spring-cloud-albaba?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true
    password: Bz5jdUgzdo6HXA7x
    username: douchacha
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 5
      auto-commit: true
      pool-name: dcc-hikari-cp
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select now()

